# Creates (or re-keys) the local Qabas development role and databases on the native
# PostgreSQL 16 service, then writes backend/.env with the connection URLs.
#
#   Role:      qabas (LOGIN, CREATEDB) with a freshly generated password
#   Databases: qabas_dev, qabas_test (UTF8, owned by qabas)
#
# You are prompted for the postgres superuser password; it is used only for this run
# and is never written to disk. Re-running is safe: existing objects are kept and the
# qabas password is rotated (backend/.env is rewritten to match).
$ErrorActionPreference = 'Stop'

$psql = 'C:\Program Files\PostgreSQL\16\bin\psql.exe'
if (-not (Test-Path $psql)) { throw "psql not found at $psql" }

$backendDir = Resolve-Path (Join-Path $PSScriptRoot '..\..')
$envFile = Join-Path $backendDir '.env'

$secure = Read-Host -AsSecureString 'postgres superuser password'
$bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
try { $env:PGPASSWORD = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr) }
finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }

# 32 random bytes, hex-encoded: URL-safe and SQL-literal-safe.
$bytes = New-Object byte[] 32
[Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
$rolePassword = -join ($bytes | ForEach-Object { $_.ToString('x2') })

function Invoke-Psql([string]$db, [string]$sql) {
    $out = $sql | & $psql -h 127.0.0.1 -p 5432 -U postgres -d $db -v ON_ERROR_STOP=1 -q -t -A -f - 2>&1
    if ($LASTEXITCODE -ne 0) { throw "psql failed: $out" }
    return $out
}

try {
    Invoke-Psql 'postgres' @"
DO `$`$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'qabas') THEN
    CREATE ROLE qabas LOGIN CREATEDB PASSWORD '$rolePassword';
  ELSE
    ALTER ROLE qabas WITH LOGIN CREATEDB PASSWORD '$rolePassword';
  END IF;
END
`$`$;
"@ | Out-Null

    foreach ($db in 'qabas_dev', 'qabas_test') {
        $exists = Invoke-Psql 'postgres' "SELECT 1 FROM pg_database WHERE datname = '$db';"
        if (-not $exists) {
            Invoke-Psql 'postgres' "CREATE DATABASE $db OWNER qabas ENCODING 'UTF8' TEMPLATE template0;" | Out-Null
            Write-Host "Created database $db"
        } else {
            Write-Host "Database $db already exists"
        }
        Invoke-Psql $db "ALTER SCHEMA public OWNER TO qabas;" | Out-Null
    }
}
finally { Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue }

@"
# Local development settings (generated by scripts/dev/create-dev-db.ps1). Never commit.
DATABASE_URL=postgresql+asyncpg://qabas:$rolePassword@127.0.0.1:5432/qabas_dev
TEST_DATABASE_URL=postgresql+asyncpg://qabas:$rolePassword@127.0.0.1:5432/qabas_test
REDIS_URL=redis://127.0.0.1:6379/0
"@ | Set-Content -Path $envFile -Encoding ascii

Write-Host "Role 'qabas' ready; connection URLs written to $envFile"
