"""Core schema: users/auth, curriculum and versioned content, learner state, sessions, XP/quests,
outbox and gate audit, with every mandatory constraint from the data model.

Integrity that a CHECK cannot express is enforced by triggers for every database role:
published content immutability, set-once concept introduction, frozen session snapshots and
terminal sessions, insert-only answers and gate decisions, and published current versions.
Custom SQLSTATEs: QB001 immutable published content, QB002 set-once field, QB003 session
snapshot/terminal state, QB004 insert-only row, QB005 current version not published.

Revision ID: 0001
Revises:
Create Date: 2026-10-04
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deletion_jobs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "steps", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deletion_jobs")),
    )
    op.create_index(
        "uq_deletion_jobs_user_id_pending",
        "deletion_jobs",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("completed_at IS NULL"),
    )
    op.create_table(
        "effect_ledger",
        sa.Column("effect_key", sa.Text(), nullable=False),
        sa.Column("event_key", sa.Text(), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("effect_key", name=op.f("pk_effect_ledger")),
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_key", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_outbox_events_attempts_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("event_key", name=op.f("uq_outbox_events_event_key")),
    )
    op.create_index(
        "ix_outbox_events_pending",
        "outbox_events",
        ["available_at"],
        unique=False,
        postgresql_where=sa.text("processed_at IS NULL"),
    )
    op.create_table(
        "scene_versions",
        sa.Column("scene_id", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("manifest_url", sa.Text(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("view_box", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("states", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("required_capabilities", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
        sa.Column(
            "anchors", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("fallback_image", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("preview", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("audit", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.Text(), server_default="draft", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_run_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'published') = (published_at IS NOT NULL)", name=op.f("ck_scene_versions_published_status")
        ),
        sa.CheckConstraint("scene_id ~ '^scn_[0-9A-Za-z_]+$'", name=op.f("ck_scene_versions_scene_id_format")),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_scene_versions_sha256_format")),
        sa.CheckConstraint("status IN ('draft', 'published')", name=op.f("ck_scene_versions_status_valid")),
        sa.CheckConstraint("bytes > 0", name=op.f("ck_scene_versions_bytes_positive")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_scene_versions_version_positive")),
        sa.PrimaryKeyConstraint("scene_id", "version", name="pk_scene_versions"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=True),
        sa.Column("provider_record_id", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("reference", sa.Text(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column(
            "raw", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("text_sha256", sa.Text(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("adapter_version", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("id ~ '^src_[0-9A-Za-z_]+$'", name=op.f("ck_sources_id_format")),
        sa.CheckConstraint(
            "kind IN ('quran', 'hadith', 'tafsir', 'article', 'book', 'fatwa')", name=op.f("ck_sources_kind_valid")
        ),
        sa.CheckConstraint(
            "provider IS NULL OR provider IN ('tafsir_center', 'quran_com', 'hadeethenc', 'quranenc', 'islamhouse', 'dorar')",
            name=op.f("ck_sources_provider_valid"),
        ),
        sa.CheckConstraint(
            "text_sha256 IS NULL OR text_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_sources_text_sha256_format")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_index(
        "uq_sources_provider_record",
        "sources",
        ["provider", "provider_record_id"],
        unique=True,
        postgresql_where=sa.text("provider_record_id IS NOT NULL"),
    )
    op.create_table(
        "units",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("title", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("subtitle", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("art_key", sa.Text(), nullable=True),
        sa.Column("guide", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tracks", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("coming_soon", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("pass_percent", sa.SmallInteger(), server_default="80", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "cardinality(tracks) >= 1 AND tracks <@ ARRAY['explorer', 'new_muslim']::text[]",
            name=op.f("ck_units_tracks_valid"),
        ),
        sa.CheckConstraint("id ~ '^unit_[0-9A-Za-z_]+$'", name=op.f("ck_units_id_format")),
        sa.CheckConstraint("index >= 0", name=op.f("ck_units_index_non_negative")),
        sa.CheckConstraint("pass_percent BETWEEN 1 AND 100", name=op.f("ck_units_pass_percent_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
        sa.UniqueConstraint("index", name=op.f("uq_units_index")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("avatar_key", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), server_default="learner", nullable=False),
        sa.Column("language", sa.Text(), server_default="ar", nullable=False),
        sa.Column("track", sa.Text(), server_default="explorer", nullable=False),
        sa.Column("familiarity", sa.Text(), nullable=True),
        sa.Column("daily_goal_minutes", sa.SmallInteger(), server_default="10", nullable=False),
        sa.Column("private_profile", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column("onboarding_completed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("goal_anchor", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_bot", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(role = 'reviewer') = (email IS NOT NULL AND password_hash IS NOT NULL)",
            name=op.f("ck_users_reviewer_credentials"),
        ),
        sa.CheckConstraint(
            "familiarity IS NULL OR familiarity IN ('none', 'some', 'good')", name=op.f("ck_users_familiarity_valid")
        ),
        sa.CheckConstraint("id ~ '^usr_[0-9A-Za-z_]+$'", name=op.f("ck_users_id_format")),
        sa.CheckConstraint("language IN ('ar', 'en')", name=op.f("ck_users_language_valid")),
        sa.CheckConstraint("role IN ('learner', 'reviewer')", name=op.f("ck_users_role_valid")),
        sa.CheckConstraint("track IN ('explorer', 'new_muslim')", name=op.f("ck_users_track_valid")),
        sa.CheckConstraint("NOT (is_bot AND is_synthetic)", name=op.f("ck_users_bot_or_synthetic")),
        sa.CheckConstraint("daily_goal_minutes IN (5, 10, 15, 20)", name=op.f("ck_users_daily_goal_minutes_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "uq_users_email_lower",
        "users",
        [sa.literal_column("lower(email)")],
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("token_hmac", sa.LargeBinary(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role IN ('learner', 'reviewer')", name=op.f("ck_auth_sessions_role_valid")),
        sa.CheckConstraint("octet_length(token_hmac) = 32", name=op.f("ck_auth_sessions_token_hmac_length")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("token_hmac", name=op.f("uq_auth_sessions_token_hmac")),
    )
    op.create_index(
        "ix_auth_sessions_user_id_active",
        "auth_sessions",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "concepts",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("unit_id", sa.Text(), nullable=False),
        sa.Column("title", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prerequisite_ids", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
        sa.Column("introduced_by_lesson_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("id ~ '^con_[0-9A-Za-z_]+$'", name=op.f("ck_concepts_id_format")),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], name=op.f("fk_concepts_unit_id_units")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concepts")),
    )
    op.create_index("ix_concepts_unit_id", "concepts", ["unit_id"], unique=False)
    op.create_table(
        "daily_activity",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("minutes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("xp", sa.Integer(), server_default="0", nullable=False),
        sa.Column("qualifying", sa.Boolean(), server_default="false", nullable=False),
        sa.CheckConstraint("minutes >= 0 AND xp >= 0", name=op.f("ck_daily_activity_counters_non_negative")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_daily_activity_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "local_date", name="pk_daily_activity"),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("response_status", sa.SmallInteger(), nullable=False),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("request_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_idempotency_keys_request_hash_format")),
        sa.CheckConstraint(
            "response_status BETWEEN 100 AND 599", name=op.f("ck_idempotency_keys_response_status_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_idempotency_keys_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "key", name=op.f("pk_idempotency_keys")),
    )
    op.create_index("ix_idempotency_keys_created_at", "idempotency_keys", ["created_at"], unique=False)
    op.create_table(
        "learner_units",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("unit_id", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pretest_taken_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pretest_percent", sa.SmallInteger(), nullable=True),
        sa.Column("unit_test_best_percent", sa.SmallInteger(), nullable=True),
        sa.Column("unit_test_passed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_post_percent", sa.SmallInteger(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("skipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(pretest_taken_at IS NULL) = (pretest_percent IS NULL)", name=op.f("ck_learner_units_pretest_recorded")
        ),
        sa.CheckConstraint(
            "first_post_percent IS NULL OR first_post_percent BETWEEN 0 AND 100",
            name=op.f("ck_learner_units_first_post_percent_range"),
        ),
        sa.CheckConstraint(
            "pretest_percent IS NULL OR pretest_percent BETWEEN 0 AND 100",
            name=op.f("ck_learner_units_pretest_percent_range"),
        ),
        sa.CheckConstraint(
            "unit_test_best_percent IS NULL OR unit_test_best_percent BETWEEN 0 AND 100",
            name=op.f("ck_learner_units_unit_test_best_percent_range"),
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], name=op.f("fk_learner_units_unit_id_units")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learner_units_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "unit_id", name="pk_learner_units"),
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("unit_id", sa.Text(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("lesson_type", sa.Text(), nullable=False),
        sa.Column("estimated_minutes", sa.SmallInteger(), nullable=False),
        sa.Column("xp", sa.SmallInteger(), server_default="10", nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=True),
        sa.Column("is_gold", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "prerequisite_concept_ids", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False
        ),
        sa.Column(
            "introduced_concept_ids", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False
        ),
        sa.Column("standalone_eligible", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("variants", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("id ~ '^les_[0-9A-Za-z_]+$'", name=op.f("ck_lessons_id_format")),
        sa.CheckConstraint(
            "lesson_type IN ('concept', 'story', 'practice')", name=op.f("ck_lessons_lesson_type_valid")
        ),
        sa.CheckConstraint(
            "variants <@ ARRAY['explorer', 'new_muslim']::text[]", name=op.f("ck_lessons_variants_valid")
        ),
        sa.CheckConstraint(
            "NOT standalone_eligible OR cardinality(prerequisite_concept_ids) = 0",
            name=op.f("ck_lessons_standalone_without_prerequisites"),
        ),
        sa.CheckConstraint("estimated_minutes > 0", name=op.f("ck_lessons_estimated_minutes_positive")),
        sa.CheckConstraint("index >= 1", name=op.f("ck_lessons_index_positive")),
        sa.CheckConstraint("xp >= 0", name=op.f("ck_lessons_xp_non_negative")),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], name=op.f("fk_lessons_unit_id_units")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons")),
        sa.UniqueConstraint("unit_id", "index", name="uq_lessons_unit_id_index"),
    )
    op.create_table(
        "quests",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("slot", sa.SmallInteger(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("goal", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reward_xp", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('earn_xp', 'complete_lessons', 'perfect_lesson', 'complete_review', 'win_challenge', 'recite_verse')",
            name=op.f("ck_quests_kind_valid"),
        ),
        sa.CheckConstraint("completed_at IS NULL OR progress >= goal", name=op.f("ck_quests_completed_when_goal_met")),
        sa.CheckConstraint("goal > 0 AND progress >= 0 AND reward_xp >= 0", name=op.f("ck_quests_amounts_valid")),
        sa.CheckConstraint("slot BETWEEN 1 AND 3", name=op.f("ck_quests_slot_range")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_quests_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quests")),
        sa.UniqueConstraint("user_id", "local_date", "kind", name="uq_quests_kind"),
        sa.UniqueConstraint("user_id", "local_date", "slot", name="uq_quests_slot"),
    )
    op.create_table(
        "recitation_checks",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("surah", sa.SmallInteger(), nullable=False),
        sa.Column("ayah", sa.SmallInteger(), nullable=False),
        sa.Column("word_start", sa.SmallInteger(), nullable=True),
        sa.Column("word_end", sa.SmallInteger(), nullable=True),
        sa.Column("checked_text_sha256", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("words", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "checked_text_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_recitation_checks_checked_text_sha256_format")
        ),
        sa.CheckConstraint("id ~ '^rchk_[0-9A-Za-z_]+$'", name=op.f("ck_recitation_checks_id_format")),
        sa.CheckConstraint(
            "status = 'evaluated' OR NOT passed", name=op.f("ck_recitation_checks_unclear_never_passes")
        ),
        sa.CheckConstraint("status IN ('evaluated', 'unclear')", name=op.f("ck_recitation_checks_status_valid")),
        sa.CheckConstraint(
            "(word_start IS NULL AND word_end IS NULL) OR (word_start IS NOT NULL AND word_end IS NOT NULL AND word_start >= 1 AND word_end >= word_start)",
            name=op.f("ck_recitation_checks_word_range_valid"),
        ),
        sa.CheckConstraint("ayah >= 1", name=op.f("ck_recitation_checks_ayah_positive")),
        sa.CheckConstraint("surah BETWEEN 1 AND 114", name=op.f("ck_recitation_checks_surah_range")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_recitation_checks_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recitation_checks")),
    )
    op.create_index("ix_recitation_checks_user_id", "recitation_checks", ["user_id"], unique=False)
    op.create_table(
        "scene_assets",
        sa.Column("scene_id", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "mime_type IN ('image/svg+xml', 'image/webp', 'image/png', 'image/jpeg')",
            name=op.f("ck_scene_assets_mime_type_valid"),
        ),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_scene_assets_sha256_format")),
        sa.CheckConstraint("width > 0 AND height > 0 AND bytes > 0", name=op.f("ck_scene_assets_dimensions_positive")),
        sa.ForeignKeyConstraint(
            ["scene_id", "version"],
            ["scene_versions.scene_id", "scene_versions.version"],
            name="fk_scene_assets_scene_versions",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("scene_id", "version", "asset_id", name="pk_scene_assets"),
    )
    op.create_table(
        "xp_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("ref_type", sa.Text(), nullable=False),
        sa.Column("ref_id", sa.Text(), nullable=False),
        sa.Column("week_key", sa.Text(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "reason IN ('lesson_complete', 'lesson_perfect', 'recitation_passed', 'review_complete', 'pretest_complete', 'unit_test_passed', 'duel_win', 'duel_draw', 'duel_loss', 'group_rank_1', 'group_rank_2', 'group_rank_other', 'daily_goal_met', 'quest_complete')",
            name=op.f("ck_xp_events_reason_valid"),
        ),
        sa.CheckConstraint("xp >= 0", name=op.f("ck_xp_events_xp_non_negative")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_xp_events_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_xp_events")),
        sa.UniqueConstraint("user_id", "reason", "ref_type", "ref_id", name="uq_xp_events_grant"),
    )
    op.create_index("ix_xp_events_user_id_week_key", "xp_events", ["user_id", "week_key"], unique=False)
    op.create_index(
        "uq_xp_events_daily_goal",
        "xp_events",
        ["user_id", "local_date"],
        unique=True,
        postgresql_where=sa.text("reason = 'daily_goal_met'"),
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("lesson_id", sa.Text(), nullable=True),
        sa.Column("unit_id", sa.Text(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("concept_ids", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("id ~ '^ex_[0-9A-Za-z_]+$'", name=op.f("ck_exercises_id_format")),
        sa.CheckConstraint(
            "purpose <> 'duel' OR type IN ('multiple_choice', 'true_false', 'verse_meaning')",
            name=op.f("ck_exercises_duel_type_allowed"),
        ),
        sa.CheckConstraint(
            "purpose <> 'lesson' OR lesson_id IS NOT NULL", name=op.f("ck_exercises_lesson_exercise_has_lesson")
        ),
        sa.CheckConstraint(
            "purpose = 'lesson' OR type NOT IN ('recite_verse', 'flashcard')",
            name=op.f("ck_exercises_assessment_type_allowed"),
        ),
        sa.CheckConstraint(
            "purpose IN ('lesson', 'pretest', 'unit_test', 'duel')", name=op.f("ck_exercises_purpose_valid")
        ),
        sa.CheckConstraint(
            "type IN ('multiple_choice', 'true_false_reason', 'match_pairs', 'flashcard', 'fill_blank', 'categorize', 'spot_error', 'which_evidence', 'order_steps', 'scenario', 'timeline_order', 'map_place', 'recite_verse', 'verse_meaning', 'true_false')",
            name=op.f("ck_exercises_type_valid"),
        ),
        sa.CheckConstraint("type NOT IN ('true_false') OR purpose = 'duel'", name=op.f("ck_exercises_duel_only_type")),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], name=op.f("fk_exercises_lesson_id_lessons")),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], name=op.f("fk_exercises_unit_id_units")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercises")),
    )
    op.create_index("ix_exercises_lesson_id", "exercises", ["lesson_id"], unique=False)
    op.create_index("ix_exercises_unit_id_purpose", "exercises", ["unit_id", "purpose"], unique=False)
    op.create_table(
        "learner_concepts",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("concept_id", sa.Text(), nullable=False),
        sa.Column("mastery", sa.Numeric(precision=7, scale=6), server_default="0", nullable=False),
        sa.Column("fsrs_card", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_practiced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("mastery BETWEEN 0 AND 1", name=op.f("ck_learner_concepts_mastery_range")),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], name=op.f("fk_learner_concepts_concept_id_concepts")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learner_concepts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "concept_id", name="pk_learner_concepts"),
    )
    op.create_index("ix_learner_concepts_user_id_due_at", "learner_concepts", ["user_id", "due_at"], unique=False)
    op.create_table(
        "learner_lessons",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("lesson_id", sa.Text(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("best_percent", sa.SmallInteger(), nullable=True),
        sa.Column("completed_session_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "best_percent IS NULL OR best_percent BETWEEN 0 AND 100", name=op.f("ck_learner_lessons_best_percent_range")
        ),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], name=op.f("fk_learner_lessons_lesson_id_lessons")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learner_lessons_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "lesson_id", name="pk_learner_lessons"),
    )
    op.create_table(
        "lesson_versions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("lesson_id", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("reviewed_by", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("run_id", sa.Text(), nullable=True),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("arc_map", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.Text(), nullable=False),
        sa.Column("contract_revision", sa.SmallInteger(), nullable=False),
        sa.Column("scene_schema", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_lesson_versions_content_sha256_format")),
        sa.CheckConstraint("contract_revision >= 10", name=op.f("ck_lesson_versions_contract_revision_supported")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_lesson_versions_version_positive")),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], name=op.f("fk_lesson_versions_lesson_id_lessons")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lesson_versions")),
        sa.UniqueConstraint("lesson_id", "version", name="uq_lesson_versions_lesson_id_version"),
    )
    op.create_table(
        "misconceptions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("unit_id", sa.Text(), nullable=False),
        sa.Column("concept_id", sa.Text(), nullable=True),
        sa.Column("title", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("card", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_ids", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("id ~ '^mis_[0-9A-Za-z_]+$'", name=op.f("ck_misconceptions_id_format")),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], name=op.f("fk_misconceptions_concept_id_concepts")),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], name=op.f("fk_misconceptions_unit_id_units")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_misconceptions")),
    )
    op.create_table(
        "terms",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("text", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("arabic", sa.Text(), nullable=True),
        sa.Column("transliteration", sa.Text(), nullable=True),
        sa.Column("concept_id", sa.Text(), nullable=True),
        sa.Column("lesson_id", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Text(), nullable=True),
        sa.Column("pronunciation_audio_url", sa.Text(), nullable=True),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("example", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("id ~ '^term_[0-9A-Za-z_]+$'", name=op.f("ck_terms_id_format")),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], name=op.f("fk_terms_concept_id_concepts")),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], name=op.f("fk_terms_lesson_id_lessons")),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], name=op.f("fk_terms_source_id_sources")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_terms")),
    )
    op.create_index("ix_terms_concept_id", "terms", ["concept_id"], unique=False)
    op.create_table(
        "claims",
        sa.Column("lesson_version_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("basis", sa.Text(), nullable=False),
        sa.Column(
            "evidence", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("reasoning", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "basis = 'reasoning' OR reasoning IS NULL", name=op.f("ck_claims_reasoning_only_for_reasoning_basis")
        ),
        sa.CheckConstraint("basis IN ('source', 'reasoning')", name=op.f("ck_claims_basis_valid")),
        sa.CheckConstraint("id ~ '^clm_[0-9A-Za-z_]+$'", name=op.f("ck_claims_id_format")),
        sa.CheckConstraint("status IN ('supported', 'dropped')", name=op.f("ck_claims_status_valid")),
        sa.ForeignKeyConstraint(
            ["lesson_version_id"],
            ["lesson_versions.id"],
            name=op.f("fk_claims_lesson_version_id_lesson_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("lesson_version_id", "id", name="pk_claims"),
    )
    op.create_table(
        "exercise_versions",
        sa.Column("exercise_id", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scoring", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("framing", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("answer_key", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "option_misconceptions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("targets_misconception_id", sa.Text(), nullable=True),
        sa.Column("source_ids", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
        sa.Column("duel_eligible", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("lesson_version_id", sa.UUID(), nullable=True),
        sa.Column("content_sha256", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_exercise_versions_content_sha256_format")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_exercise_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["exercise_id"], ["exercises.id"], name=op.f("fk_exercise_versions_exercise_id_exercises")
        ),
        sa.ForeignKeyConstraint(
            ["lesson_version_id"],
            ["lesson_versions.id"],
            name=op.f("fk_exercise_versions_lesson_version_id_lesson_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["targets_misconception_id"],
            ["misconceptions.id"],
            name=op.f("fk_exercise_versions_targets_misconception_id_misconceptions"),
        ),
        sa.PrimaryKeyConstraint("exercise_id", "version", name="pk_exercise_versions"),
    )
    op.create_table(
        "learner_misconceptions",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("misconception_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="inactive", nullable=False),
        sa.Column("evidence_score", sa.Numeric(precision=6, scale=2), server_default="0", nullable=False),
        sa.Column("correct_streak", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'resolved') = (resolved_at IS NOT NULL)",
            name=op.f("ck_learner_misconceptions_resolution_recorded"),
        ),
        sa.CheckConstraint(
            "status = 'inactive' OR activated_at IS NOT NULL",
            name=op.f("ck_learner_misconceptions_activation_recorded"),
        ),
        sa.CheckConstraint(
            "status IN ('inactive', 'active', 'resolved')", name=op.f("ck_learner_misconceptions_status_valid")
        ),
        sa.CheckConstraint(
            "correct_streak BETWEEN 0 AND 3", name=op.f("ck_learner_misconceptions_correct_streak_range")
        ),
        sa.CheckConstraint("evidence_score >= 0", name=op.f("ck_learner_misconceptions_evidence_non_negative")),
        sa.ForeignKeyConstraint(
            ["misconception_id"],
            ["misconceptions.id"],
            name=op.f("fk_learner_misconceptions_misconception_id_misconceptions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learner_misconceptions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "misconception_id", name="pk_learner_misconceptions"),
    )
    op.create_table(
        "learner_terms",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("term_id", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), server_default="new", nullable=False),
        sa.Column("exposures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("opened_count", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint("state IN ('new', 'learning', 'mastered')", name=op.f("ck_learner_terms_state_valid")),
        sa.CheckConstraint("exposures >= 0 AND opened_count >= 0", name=op.f("ck_learner_terms_counters_non_negative")),
        sa.ForeignKeyConstraint(["term_id"], ["terms.id"], name=op.f("fk_learner_terms_term_id_terms")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learner_terms_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "term_id", name="pk_learner_terms"),
    )
    op.create_table(
        "review_decisions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=True),
        sa.Column("lesson_version_id", sa.UUID(), nullable=True),
        sa.Column("gate", sa.SmallInteger(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("reviewer_id", sa.Text(), nullable=False),
        sa.Column("reviewed_digest", sa.Text(), nullable=False),
        sa.Column("published_digest", sa.Text(), nullable=True),
        sa.Column(
            "edits", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "decision IN ('approve', 'reject', 'request_changes')", name=op.f("ck_review_decisions_decision_valid")
        ),
        sa.CheckConstraint(
            "gate = 2 OR decision IN ('approve', 'reject')", name=op.f("ck_review_decisions_gate1_decision")
        ),
        sa.CheckConstraint(
            "published_digest IS NULL OR (gate = 2 AND decision = 'approve')",
            name=op.f("ck_review_decisions_published_only_on_gate2_approve"),
        ),
        sa.CheckConstraint(
            "published_digest IS NULL OR published_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_review_decisions_published_digest_format"),
        ),
        sa.CheckConstraint(
            "reviewed_digest ~ '^[0-9a-f]{64}$'", name=op.f("ck_review_decisions_reviewed_digest_format")
        ),
        sa.CheckConstraint("gate IN (1, 2)", name=op.f("ck_review_decisions_gate_valid")),
        sa.CheckConstraint(
            "run_id IS NOT NULL OR lesson_version_id IS NOT NULL", name=op.f("ck_review_decisions_has_subject")
        ),
        sa.ForeignKeyConstraint(
            ["lesson_version_id"],
            ["lesson_versions.id"],
            name=op.f("fk_review_decisions_lesson_version_id_lesson_versions"),
        ),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], name=op.f("fk_review_decisions_reviewer_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_decisions")),
    )
    op.create_index("ix_review_decisions_lesson_version_id", "review_decisions", ["lesson_version_id"], unique=False)
    op.create_index("ix_review_decisions_run_id", "review_decisions", ["run_id"], unique=False)
    op.create_table(
        "sentences",
        sa.Column("lesson_version_id", sa.UUID(), nullable=False),
        sa.Column("lang", sa.Text(), nullable=False),
        sa.Column("variant", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("claim_ids", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
        sa.Column("edited_by_reviewer", sa.Boolean(), server_default="false", nullable=False),
        sa.CheckConstraint(
            "(role = 'claim') = (cardinality(claim_ids) > 0)", name=op.f("ck_sentences_claim_links_match_role")
        ),
        sa.CheckConstraint("id ~ '^sen_[0-9A-Za-z_]+$'", name=op.f("ck_sentences_id_format")),
        sa.CheckConstraint("lang IN ('ar', 'en')", name=op.f("ck_sentences_lang_valid")),
        sa.CheckConstraint(
            "role IN ('claim', 'framing', 'hypothetical', 'instruction', 'question')",
            name=op.f("ck_sentences_role_valid"),
        ),
        sa.CheckConstraint("variant IN ('explorer', 'new_muslim')", name=op.f("ck_sentences_variant_valid")),
        sa.ForeignKeyConstraint(
            ["lesson_version_id"],
            ["lesson_versions.id"],
            name=op.f("fk_sentences_lesson_version_id_lesson_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("lesson_version_id", "lang", "variant", "id", name="pk_sentences"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=True),
        sa.Column("lesson_id", sa.Text(), nullable=True),
        sa.Column("lesson_version_id", sa.UUID(), nullable=True),
        sa.Column("unit_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("feedback_mode", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), nullable=False),
        sa.Column("variant", sa.Text(), nullable=False),
        sa.Column("items_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("served_exercises", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "served_scenes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("abandoned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("result_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("contract_revision", sa.SmallInteger(), nullable=False),
        sa.Column("snapshot_revision", sa.SmallInteger(), nullable=True),
        sa.CheckConstraint(
            "(kind = 'lesson' AND feedback_mode = 'immediate') OR (kind = 'review' AND feedback_mode = 'immediate') OR (kind = 'pretest' AND feedback_mode = 'none') OR (kind = 'unit_test' AND feedback_mode = 'end')",
            name=op.f("ck_sessions_feedback_mode_matches_kind"),
        ),
        sa.CheckConstraint("(kind = 'review') = (mode IS NOT NULL)", name=op.f("ck_sessions_mode_only_for_review")),
        sa.CheckConstraint(
            "(status = 'abandoned') = (abandoned_at IS NOT NULL)", name=op.f("ck_sessions_abandoned_recorded")
        ),
        sa.CheckConstraint(
            "(status = 'finished') = (finished_at IS NOT NULL AND result_snapshot IS NOT NULL)",
            name=op.f("ck_sessions_finished_has_result"),
        ),
        sa.CheckConstraint(
            "feedback_mode IN ('immediate', 'none', 'end')", name=op.f("ck_sessions_feedback_mode_valid")
        ),
        sa.CheckConstraint("id ~ '^ses_[0-9A-Za-z_]+$'", name=op.f("ck_sessions_id_format")),
        sa.CheckConstraint(
            "kind <> 'lesson' OR (lesson_id IS NOT NULL AND lesson_version_id IS NOT NULL AND unit_id IS NOT NULL)",
            name=op.f("ck_sessions_lesson_session_refs"),
        ),
        sa.CheckConstraint(
            "kind = 'lesson' OR (lesson_id IS NULL AND lesson_version_id IS NULL)",
            name=op.f("ck_sessions_lesson_refs_only_for_lessons"),
        ),
        sa.CheckConstraint("kind IN ('lesson', 'review', 'pretest', 'unit_test')", name=op.f("ck_sessions_kind_valid")),
        sa.CheckConstraint(
            "kind NOT IN ('pretest', 'unit_test') OR unit_id IS NOT NULL", name=op.f("ck_sessions_unit_session_refs")
        ),
        sa.CheckConstraint("language IN ('ar', 'en')", name=op.f("ck_sessions_language_valid")),
        sa.CheckConstraint("mode IS NULL OR mode IN ('cards', 'quick')", name=op.f("ck_sessions_mode_valid")),
        sa.CheckConstraint(
            "status = 'finished' OR (finished_at IS NULL AND result_snapshot IS NULL AND duration_ms IS NULL)",
            name=op.f("ck_sessions_result_only_when_finished"),
        ),
        sa.CheckConstraint("status IN ('active', 'finished', 'abandoned')", name=op.f("ck_sessions_status_valid")),
        sa.CheckConstraint("variant IN ('explorer', 'new_muslim')", name=op.f("ck_sessions_variant_valid")),
        sa.CheckConstraint("duration_ms IS NULL OR duration_ms >= 0", name=op.f("ck_sessions_duration_non_negative")),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], name=op.f("fk_sessions_lesson_id_lessons")),
        sa.ForeignKeyConstraint(
            ["lesson_version_id"], ["lesson_versions.id"], name=op.f("fk_sessions_lesson_version_id_lesson_versions")
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], name=op.f("fk_sessions_unit_id_units")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index("ix_sessions_user_id_started_at", "sessions", ["user_id", "started_at"], unique=False)
    op.create_index(
        "uq_sessions_one_active",
        "sessions",
        [
            "user_id",
            "kind",
            sa.literal_column("COALESCE(lesson_id, '')"),
            sa.literal_column("COALESCE(unit_id, '')"),
            sa.literal_column("COALESCE(mode, '')"),
        ],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "session_answers",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("exercise_id", sa.Text(), nullable=False),
        sa.Column("exercise_version", sa.Integer(), nullable=False),
        sa.Column("answer", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("correct", sa.Boolean(), nullable=True),
        sa.Column("elapsed_ms", sa.Integer(), nullable=True),
        sa.Column("is_retry", sa.Boolean(), nullable=False),
        sa.Column("misconception_id", sa.Text(), nullable=True),
        sa.Column("evaluation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "elapsed_ms IS NULL OR elapsed_ms >= 0", name=op.f("ck_session_answers_elapsed_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id", "exercise_version"],
            ["exercise_versions.exercise_id", "exercise_versions.version"],
            name="fk_session_answers_exercise_versions",
        ),
        sa.ForeignKeyConstraint(
            ["misconception_id"], ["misconceptions.id"], name=op.f("fk_session_answers_misconception_id_misconceptions")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_session_answers_session_id_sessions"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_answers")),
        sa.UniqueConstraint("session_id", "exercise_id", "is_retry", name="uq_session_answers_identity"),
    )
    # ### end Alembic commands ###

    op.create_foreign_key(
        "fk_concepts_introduced_by_lesson_id_lessons", "concepts", "lessons", ["introduced_by_lesson_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_lessons_current_version_lesson_versions",
        "lessons",
        "lesson_versions",
        ["id", "current_version"],
        ["lesson_id", "version"],
    )
    op.create_foreign_key(
        "fk_exercises_current_version_exercise_versions",
        "exercises",
        "exercise_versions",
        ["id", "current_version"],
        ["exercise_id", "version"],
    )
    for statement in INTEGRITY_SQL:
        op.execute(statement)
    op.execute(GRANTS_FUNCTION)
    op.execute("SELECT qabas_apply_grants()")


def downgrade() -> None:
    op.drop_constraint("fk_exercises_current_version_exercise_versions", "exercises", type_="foreignkey")
    op.drop_constraint("fk_lessons_current_version_lesson_versions", "lessons", type_="foreignkey")
    op.drop_constraint("fk_concepts_introduced_by_lesson_id_lessons", "concepts", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_answers")
    op.drop_index("uq_sessions_one_active", table_name="sessions", postgresql_where=sa.text("status = 'active'"))
    op.drop_index("ix_sessions_user_id_started_at", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("sentences")
    op.drop_index("ix_review_decisions_run_id", table_name="review_decisions")
    op.drop_index("ix_review_decisions_lesson_version_id", table_name="review_decisions")
    op.drop_table("review_decisions")
    op.drop_table("learner_terms")
    op.drop_table("learner_misconceptions")
    op.drop_table("exercise_versions")
    op.drop_table("claims")
    op.drop_index("ix_terms_concept_id", table_name="terms")
    op.drop_table("terms")
    op.drop_table("misconceptions")
    op.drop_table("lesson_versions")
    op.drop_table("learner_lessons")
    op.drop_index("ix_learner_concepts_user_id_due_at", table_name="learner_concepts")
    op.drop_table("learner_concepts")
    op.drop_index("ix_exercises_unit_id_purpose", table_name="exercises")
    op.drop_index("ix_exercises_lesson_id", table_name="exercises")
    op.drop_table("exercises")
    op.drop_index(
        "uq_xp_events_daily_goal", table_name="xp_events", postgresql_where=sa.text("reason = 'daily_goal_met'")
    )
    op.drop_index("ix_xp_events_user_id_week_key", table_name="xp_events")
    op.drop_table("xp_events")
    op.drop_table("scene_assets")
    op.drop_index("ix_recitation_checks_user_id", table_name="recitation_checks")
    op.drop_table("recitation_checks")
    op.drop_table("quests")
    op.drop_table("lessons")
    op.drop_table("learner_units")
    op.drop_index("ix_idempotency_keys_created_at", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_table("daily_activity")
    op.drop_index("ix_concepts_unit_id", table_name="concepts")
    op.drop_table("concepts")
    op.drop_index(
        "ix_auth_sessions_user_id_active", table_name="auth_sessions", postgresql_where=sa.text("revoked_at IS NULL")
    )
    op.drop_table("auth_sessions")
    op.drop_index("uq_users_email_lower", table_name="users", postgresql_where=sa.text("email IS NOT NULL"))
    op.drop_table("users")
    op.drop_table("units")
    op.drop_index(
        "uq_sources_provider_record", table_name="sources", postgresql_where=sa.text("provider_record_id IS NOT NULL")
    )
    op.drop_table("sources")
    op.drop_table("scene_versions")
    op.drop_index(
        "ix_outbox_events_pending", table_name="outbox_events", postgresql_where=sa.text("processed_at IS NULL")
    )
    op.drop_table("outbox_events")
    op.drop_table("effect_ledger")
    op.drop_index(
        "uq_deletion_jobs_user_id_pending", table_name="deletion_jobs", postgresql_where=sa.text("completed_at IS NULL")
    )
    op.drop_table("deletion_jobs")
    # ### end Alembic commands ###
    for function in DROP_FUNCTIONS:
        op.execute(f"DROP FUNCTION IF EXISTS {function}")


# --------------------------------------------------------------------------- integrity triggers

INTEGRITY_SQL = [
    # Published lesson/exercise/scene versions are immutable (AD-07). Draft rows may change, and
    # publishing (setting published_at) is the last write a version ever receives.
    """
    CREATE FUNCTION qabas_forbid_published_change() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF OLD.published_at IS NOT NULL THEN
            RAISE EXCEPTION 'published % rows are immutable', TG_TABLE_NAME USING ERRCODE = 'QB001';
        END IF;
        IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
        RETURN NEW;
    END $$
    """,
    *[
        f"""
        CREATE TRIGGER {table}_immutable_when_published BEFORE UPDATE OR DELETE ON {table}
        FOR EACH ROW EXECUTE FUNCTION qabas_forbid_published_change()
        """
        for table in ("lesson_versions", "exercise_versions", "scene_versions")
    ],
    # Children of a published lesson version (claims, sentences) cannot be added, changed or removed.
    """
    CREATE FUNCTION qabas_forbid_lesson_version_child_change() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE
        parent uuid := CASE WHEN TG_OP = 'DELETE' THEN OLD.lesson_version_id ELSE NEW.lesson_version_id END;
    BEGIN
        IF EXISTS (SELECT 1 FROM lesson_versions WHERE id = parent AND published_at IS NOT NULL)
           OR (TG_OP = 'UPDATE' AND EXISTS (SELECT 1 FROM lesson_versions
                                             WHERE id = OLD.lesson_version_id AND published_at IS NOT NULL)) THEN
            RAISE EXCEPTION '% of a published lesson version are immutable', TG_TABLE_NAME USING ERRCODE = 'QB001';
        END IF;
        IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
        RETURN NEW;
    END $$
    """,
    *[
        f"""
        CREATE TRIGGER {table}_immutable_when_published BEFORE INSERT OR UPDATE OR DELETE ON {table}
        FOR EACH ROW EXECUTE FUNCTION qabas_forbid_lesson_version_child_change()
        """
        for table in ("claims", "sentences")
    ],
    # Assets of a published scene version are immutable.
    """
    CREATE FUNCTION qabas_forbid_scene_asset_change() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE
        ref record;
    BEGIN
        IF TG_OP = 'DELETE' THEN ref := OLD; ELSE ref := NEW; END IF;
        IF EXISTS (SELECT 1 FROM scene_versions s WHERE s.scene_id = ref.scene_id AND s.version = ref.version
                   AND s.published_at IS NOT NULL)
           OR (TG_OP = 'UPDATE' AND EXISTS (SELECT 1 FROM scene_versions s WHERE s.scene_id = OLD.scene_id
                                             AND s.version = OLD.version AND s.published_at IS NOT NULL)) THEN
            RAISE EXCEPTION 'assets of a published scene version are immutable' USING ERRCODE = 'QB001';
        END IF;
        IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
        RETURN NEW;
    END $$
    """,
    """
    CREATE TRIGGER scene_assets_immutable_when_published BEFORE INSERT OR UPDATE OR DELETE ON scene_assets
    FOR EACH ROW EXECUTE FUNCTION qabas_forbid_scene_asset_change()
    """,
    # Each concept is introduced by exactly one lesson, set once at publication (curr).
    """
    CREATE FUNCTION qabas_concept_introduced_once() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF OLD.introduced_by_lesson_id IS NOT NULL
           AND NEW.introduced_by_lesson_id IS DISTINCT FROM OLD.introduced_by_lesson_id THEN
            RAISE EXCEPTION 'concept % is already introduced by lesson %', OLD.id, OLD.introduced_by_lesson_id
                USING ERRCODE = 'QB002';
        END IF;
        RETURN NEW;
    END $$
    """,
    """
    CREATE TRIGGER concepts_introduced_once BEFORE UPDATE OF introduced_by_lesson_id ON concepts
    FOR EACH ROW EXECUTE FUNCTION qabas_concept_introduced_once()
    """,
    # current_version may only point at a published version.
    """
    CREATE FUNCTION qabas_lesson_current_version_published() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF NEW.current_version IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM lesson_versions
            WHERE lesson_id = NEW.id AND version = NEW.current_version AND published_at IS NOT NULL) THEN
            RAISE EXCEPTION 'lesson % current_version % is not published', NEW.id, NEW.current_version
                USING ERRCODE = 'QB005';
        END IF;
        RETURN NEW;
    END $$
    """,
    """
    CREATE TRIGGER lessons_current_version_published BEFORE INSERT OR UPDATE OF current_version ON lessons
    FOR EACH ROW EXECUTE FUNCTION qabas_lesson_current_version_published()
    """,
    """
    CREATE FUNCTION qabas_exercise_current_version_published() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF NEW.current_version IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM exercise_versions
            WHERE exercise_id = NEW.id AND version = NEW.current_version AND published_at IS NOT NULL) THEN
            RAISE EXCEPTION 'exercise % current_version % is not published', NEW.id, NEW.current_version
                USING ERRCODE = 'QB005';
        END IF;
        RETURN NEW;
    END $$
    """,
    """
    CREATE TRIGGER exercises_current_version_published BEFORE INSERT OR UPDATE OF current_version ON exercises
    FOR EACH ROW EXECUTE FUNCTION qabas_exercise_current_version_published()
    """,
    # A served session keeps its snapshot; finished/abandoned sessions are terminal (finish replays
    # the stored result). A snapshot may only change through a recorded snapshot migration, which
    # must raise snapshot_revision (data model: versioning).
    """
    CREATE FUNCTION qabas_session_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF (NEW.user_id, NEW.kind, NEW.mode, NEW.lesson_id, NEW.lesson_version_id, NEW.unit_id, NEW.feedback_mode,
            NEW.language, NEW.variant, NEW.served_exercises, NEW.served_scenes, NEW.started_at, NEW.contract_revision)
           IS DISTINCT FROM
           (OLD.user_id, OLD.kind, OLD.mode, OLD.lesson_id, OLD.lesson_version_id, OLD.unit_id, OLD.feedback_mode,
            OLD.language, OLD.variant, OLD.served_exercises, OLD.served_scenes, OLD.started_at, OLD.contract_revision)
        THEN
            RAISE EXCEPTION 'session % served identity is immutable', OLD.id USING ERRCODE = 'QB003';
        END IF;
        IF NEW.items_snapshot IS DISTINCT FROM OLD.items_snapshot
           AND COALESCE(NEW.snapshot_revision, 0) <= COALESCE(OLD.snapshot_revision, 0) THEN
            RAISE EXCEPTION 'session % snapshot changed without a snapshot migration', OLD.id USING ERRCODE = 'QB003';
        END IF;
        IF OLD.status <> 'active' AND
           (NEW.status, NEW.finished_at, NEW.abandoned_at, NEW.duration_ms, NEW.result_snapshot)
           IS DISTINCT FROM
           (OLD.status, OLD.finished_at, OLD.abandoned_at, OLD.duration_ms, OLD.result_snapshot) THEN
            RAISE EXCEPTION 'session % is % and cannot change', OLD.id, OLD.status USING ERRCODE = 'QB003';
        END IF;
        RETURN NEW;
    END $$
    """,
    """
    CREATE TRIGGER sessions_guard BEFORE UPDATE ON sessions
    FOR EACH ROW EXECUTE FUNCTION qabas_session_guard()
    """,
    # Insert-only rows: recorded answers are replayed, never re-graded (AD-09); gate decisions are an audit.
    """
    CREATE FUNCTION qabas_insert_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        RAISE EXCEPTION '% rows are insert-only (% rejected)', TG_TABLE_NAME, TG_OP USING ERRCODE = 'QB004';
    END $$
    """,
    """
    CREATE TRIGGER session_answers_insert_only BEFORE UPDATE ON session_answers
    FOR EACH ROW EXECUTE FUNCTION qabas_insert_only()
    """,
    """
    CREATE TRIGGER review_decisions_insert_only BEFORE UPDATE OR DELETE ON review_decisions
    FOR EACH ROW EXECUTE FUNCTION qabas_insert_only()
    """,
]

# Least-privilege roles (data model: data protection). Roles are cluster objects created by an operator
# (backend/scripts/dev/create-dev-db.ps1 locally, the platform in deployed environments); grants apply
# only to roles that exist. Later migrations that add tables call SELECT qabas_apply_grants() again.
GRANTS_FUNCTION = """
CREATE FUNCTION qabas_apply_grants() RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    role_name text;
    no_delete text := 'units, concepts, lessons, exercises, sources, terms, misconceptions, lesson_versions, '
                      'exercise_versions, scene_versions, scene_assets, claims, sentences, review_decisions';
BEGIN
    FOREACH role_name IN ARRAY ARRAY['qabas_app', 'qabas_worker'] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
            EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', role_name);
            EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO %I', role_name);
            EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO %I', role_name);
            EXECUTE format('REVOKE DELETE ON %s FROM %I', no_delete, role_name);
            EXECUTE format('REVOKE UPDATE ON review_decisions, session_answers FROM %I', role_name);
            EXECUTE format('REVOKE INSERT, UPDATE, DELETE ON alembic_version FROM %I', role_name);
        END IF;
    END LOOP;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'qabas_readonly') THEN
        GRANT USAGE ON SCHEMA public TO qabas_readonly;
        GRANT SELECT ON ALL TABLES IN SCHEMA public TO qabas_readonly;
    END IF;
END $$
"""

DROP_FUNCTIONS = [
    "qabas_apply_grants()",
    "qabas_insert_only()",
    "qabas_session_guard()",
    "qabas_exercise_current_version_published()",
    "qabas_lesson_current_version_published()",
    "qabas_concept_introduced_once()",
    "qabas_forbid_scene_asset_change()",
    "qabas_forbid_lesson_version_child_change()",
    "qabas_forbid_published_change()",
]
